package com.neobank.auth.internal.docs;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.UUID;

/**
 * Service for managing documentation access tokens.
 * Allows SYSTEM_ADMIN to generate, list, and revoke tokens for Swagger UI access.
 */
@Service
@Transactional
public class DocTokenService {

    private static final Logger log = LoggerFactory.getLogger(DocTokenService.class);

    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final String TOKEN_PREFIX = "doc_";
    private static final int TOKEN_LENGTH = 32;

    private final DocTokenRepository tokenRepository;

    public DocTokenService(DocTokenRepository tokenRepository) {
        this.tokenRepository = tokenRepository;
    }

    /**
     * Generate a new documentation access token.
     * 
     * @param createdBy the user ID creating the token
     * @param username the username of the creator
     * @param description optional description for the token
     * @param durationHours token validity duration in hours (default 24)
     * @return the generated token entity
     */
    public DocTokenEntity generateToken(UUID createdBy, String username, String description, long durationHours) {
        String token = TOKEN_PREFIX + generateRandomString(TOKEN_LENGTH);
        
        // Ensure uniqueness
        while (tokenRepository.existsByToken(token)) {
            token = TOKEN_PREFIX + generateRandomString(TOKEN_LENGTH);
        }

        DocTokenEntity entity = new DocTokenEntity();
        entity.setId(UUID.randomUUID());
        entity.setToken(token);
        entity.setCreatedBy(createdBy);
        entity.setCreatedByUsername(username);
        entity.setDescription(description);
        entity.setCreatedAt(Instant.now());
        entity.setExpiresAt(Instant.now().plus(durationHours, ChronoUnit.HOURS));
        entity.setActive(true);

        tokenRepository.save(entity);

        log.info("Documentation access token generated by {}: {} (expires: {})", 
                username, token.substring(0, 12) + "...", entity.getExpiresAt());

        return entity;
    }

    /**
     * Generate a token with default 24-hour validity.
     */
    public DocTokenEntity generateToken(UUID createdBy, String username, String description) {
        return generateToken(createdBy, username, description, 24);
    }

    /**
     * Validate a documentation access token.
     * 
     * @param token the token to validate
     * @return the token entity if valid, null otherwise
     */
    @Transactional(readOnly = true)
    public DocTokenEntity validateToken(String token) {
        return tokenRepository.findByToken(token)
                .filter(DocTokenEntity::isValid)
                .map(entity -> {
                    entity.recordUsage();
                    tokenRepository.save(entity);
                    return entity;
                })
                .orElse(null);
    }

    /**
     * List all active tokens.
     */
    @Transactional(readOnly = true)
    public List<DocTokenEntity> listActiveTokens() {
        return tokenRepository.findByActiveTrueOrderByCreatedAtDesc();
    }

    /**
     * List tokens created by a specific user.
     */
    @Transactional(readOnly = true)
    public List<DocTokenEntity> listTokensForUser(UUID userId) {
        return tokenRepository.findByCreatedByAndActiveTrue(userId);
    }

    /**
     * Revoke a specific token.
     * 
     * @param tokenId the token entity ID to revoke
     * @return true if revoked, false if not found
     */
    public boolean revokeToken(UUID tokenId) {
        return tokenRepository.findById(tokenId)
                .map(entity -> {
                    entity.setActive(false);
                    tokenRepository.save(entity);
                    log.info("Documentation token revoked: {} (created by: {})", 
                            entity.getToken().substring(0, 12) + "...", entity.getCreatedByUsername());
                    return true;
                })
                .orElse(false);
    }

    /**
     * Revoke all tokens for a user.
     * 
     * @param userId the user ID
     * @return number of tokens revoked
     */
    public int revokeAllTokensForUser(UUID userId) {
        int count = tokenRepository.deactivateAllForUser(userId);
        log.info("All documentation tokens revoked for user {}: {} tokens", userId, count);
        return count;
    }

    /**
     * Cleanup expired tokens.
     * 
     * @return number of tokens expired
     */
    public int cleanupExpiredTokens() {
        int count = tokenRepository.expireOldTokens(Instant.now());
        if (count > 0) {
            log.info("Cleaned up {} expired documentation tokens", count);
        }
        return count;
    }

    /**
     * Generate a random string for token creation.
     */
    private String generateRandomString(int length) {
        String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            sb.append(characters.charAt(SECURE_RANDOM.nextInt(characters.length())));
        }
        return sb.toString();
    }
}
