# =============================================================================
# NeoBank Core Banking — Service (Internal ClusterIP)
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: neobank-core-banking
  namespace: neobank
  labels:
    app.kubernetes.io/name: neobank-core-banking
    app.kubernetes.io/component: core-banking
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app.kubernetes.io/name: neobank-core-banking
