# =============================================================================
# NeoBank Fraud — Service (Internal ClusterIP)
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: neobank-fraud
  namespace: neobank
  labels:
    app.kubernetes.io/name: neobank-fraud
    app.kubernetes.io/component: fraud
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    app.kubernetes.io/name: neobank-fraud
